# Baixando bibliotecas e fazendo configurações iniciais

In [29]:
import pandas as pd
import os
import numpy as np
from pprint import pprint

# ajustando algumas configurações para prints
pd.set_option('display.max_columns', None)        # todas as colunas
pd.set_option('display.max_rows', None)           # todas as linhas
pd.set_option('display.width', None)              # largura automática
pd.set_option('display.max_colwidth', None)       # conteúdo completo das células
pd.set_option('display.expand_frame_repr', False) # evita quebrar dataframe em várias linhas

In [30]:
# pegando a pasta de trabalho para poder extrair os dados do dataset
PASTA_TRABALHO = os.path.dirname(os.path.abspath(os.getcwd()))

# Lendo e armazenando todas as tabelas dos anos necessários

In [31]:
# lista com os nomes das pastas que contem os datasets
nomes_arquivos = ["2024", "2025", "2026"]

# dicionario que contêm todos os dataframes do respectivo ano no seguinte formato:
"""
    ano1:
        ocorrencia_ano1,
        acorrencia_pessoa_ano1,
        acorrencia_todas_causas_ano1
    ano2:
        ...
"""
dataframes_por_ano = {}

# percorre e salva todos as dataframes dos anos escolhidos
for ano in nomes_arquivos:
    diretorio_dataframe = os.path.join(PASTA_TRABALHO, "dataset", ano)

    # percorre todas as tabelas que existem nesse ano (só existe um arquivo)
    for tabela in os.listdir(diretorio_dataframe):

        caminho = os.path.join(diretorio_dataframe, tabela)
        data_frame = pd.read_csv(caminho, sep=";", encoding="latin1") # adiciona a tabela em questão ao dicionário temporário

    dataframes_por_ano[ano] = data_frame # adiciona a tabela de dados ao respectivo ano

## juntando as tabelas distintas dos 3 anos em somente uma tabela

In [32]:
dataset = pd.concat([df for df in dataframes_por_ano.values()])

# Tranformações

## Alterando os tipos de dados para não ter nunhum tipo de conflito com as transformações e armazenar de forma correta os dados

In [33]:
# DATA
dataset["data_inversa"] = pd.to_datetime(
    dataset["data_inversa"],
    format="%Y-%m-%d"
)


# HORÁRIO
dataset["horario"] = pd.to_datetime(
    dataset["horario"],
    format="%H:%M:%S"
).dt.time


# VALORES NUMÉRICOS
# trocando a virgula por ponto para poder converter para float
dataset["latitude"] = pd.to_numeric(
    dataset["latitude"].astype(str).str.replace(",", "."),
    errors="coerce"
)

dataset["longitude"] = pd.to_numeric(
    dataset["longitude"].astype(str).str.replace(",", "."),
    errors="coerce"
)

# passando para o tipo numérico
dataset["latitude"] = pd.to_numeric(
    dataset["latitude"],
    errors="coerce"
)

dataset["longitude"] = pd.to_numeric(
    dataset["longitude"],
    errors="coerce"
)

dataset["km"] = pd.to_numeric(
    dataset["km"].astype(str).str.replace(",", "."),
    errors="coerce"
)

dataset["km"] = pd.to_numeric(
    dataset["km"],
    errors="coerce"
)

In [34]:
# printando algumas informações pertinentes que ajudam a avaliar quais transformações são necessárias
display(dataset.shape)
display(dataset.head())
display(dataset.info())
display(dataset.describe())
display(dataset.isnull().sum())

(455060, 35)

         id    pesid data_inversa     dia_semana   horario  uf   br     km           municipio                                            causa_acidente                   tipo_acidente classificacao_acidente     fase_dia  sentido_via condicao_metereologica tipo_pista   tracado_via uso_solo  id_veiculo     tipo_veiculo                   marca  ano_fabricacao_veiculo tipo_envolvido  estado_fisico  idade       sexo  ilesos  feridos_leves  feridos_graves  mortos   latitude  longitude regional delegacia             uop
0  571789.0  1269011   2024-01-01  segunda-feira  03:56:00  ES  101   38.0  CONCEICAO DA BARRA                                    Ultrapassagem Indevida  Colisão lateral sentido oposto                    NaN  Plena Noite    Crescente              Céu Claro    Simples          Reta      Não     1018240  Caminhão-trator     M.BENZ/AXOR 2544 LS                    2014       Condutor          Ileso     46  Masculino       1              0               0       0 -18.482610 -39.923790  SPRF-ES  DEL04-ES  UOP02-DEL04-ES
1  571804.0  1269118   2024-01-01  segunda-feira  04:50:00  PI  343  185.0            PIRIPIRI                               Manobra de mudança de faixa                 Colisão frontal     Com Vítimas Fatais    Amanhecer  Decrescente              Céu Claro    Simples          Reta      Sim     1018325         Caminhão       M.BENZ/ATEGO 2426                    2019       Condutor          Ileso     24  Masculino       1              0               0       0  -4.296033 -41.767327  SPRF-PI  DEL02-PI  UOP01-DEL02-PI
2  571806.0  1269735   2024-01-01  segunda-feira  04:30:00  BA  116  578.0             BREJOES                          Ingestão de álcool pelo condutor                 Colisão frontal     Com Vítimas Fatais  Plena Noite  Decrescente              Céu Claro    Simples         Curva      Não     1018705  Caminhão-trator        SCANIA/R450 A6X2                    2021       Condutor          Ileso     45  Masculino       1              0               0       0 -13.071583 -39.961111  SPRF-BA  DEL03-BA  UOP02-DEL03-BA
3  571818.0  1269075   2024-01-01  segunda-feira  06:30:00  SE  101   18.0    MALHADA DOS BOIS                  Reação tardia ou ineficiente do condutor       Saída de leito carroçável    Com Vítimas Feridas    Amanhecer    Crescente              Céu Claro      Dupla  Declive;Reta      Não     1018287  Caminhão-trator  IVECO/STRALIS 800S48TZ                    2022       Condutor  Lesões Graves     33  Masculino       0              0               1       0 -10.356019 -36.905522  SPRF-SE  DEL02-SE  UOP02-DEL02-SE
4  571838.0  1269159   2024-01-01  segunda-feira  05:00:00  MT  364  240.0        RONDONOPOLIS  Condutor deixou de manter distância do veículo da frente                Colisão traseira            Sem Vítimas    Pleno dia    Crescente              Céu Claro      Dupla          Reta      Não     1018348         Caminhão       SCANIA/P 310 B8X2                    2013       Condutor          Ileso     57  Masculino       1              0               0       0 -16.179141 -54.789053  SPRF-MT  DEL02-MT  UOP01-DEL02-MT

<class 'pandas.core.frame.DataFrame'>
Index: 455060 entries, 0 to 64124
Data columns (total 35 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      455060 non-null  float64
 1   pesid                   455060 non-null  int64
 2   data_inversa            455060 non-null  datetime64[ns]
 3   dia_semana              455060 non-null  object
 4   horario                 455060 non-null  object
 5   uf                      455060 non-null  object
 6   br                      455060 non-null  int64
 7   km                      455060 non-null  float64
 8   municipio               455060 non-null  object
 9   causa_acidente          455060 non-null  object
 10  tipo_acidente           455060 non-null  object
 11  classificacao_acidente  455045 non-null  object
 12  fase_dia                455060 non-null  object
 13  sentido_via             455060 non-null  object
 14  condicao_metereologica  455060 non-null  object
 15  tipo_pista              455060 non-null  object
 16  tracado_via             455060 non-null  object
 17  uso_solo                455060 non-null  object
 18  id_veiculo              455060 non-null  int64
 19  tipo_veiculo            440220 non-null  object
 20  marca                   455060 non-null  object
 21  ano_fabricacao_veiculo  455060 non-null  int64
 22  tipo_envolvido          415118 non-null  object
 23  estado_fisico           415118 non-null  object
 24  idade                   455060 non-null  int64
 25  sexo                    415118 non-null  object
 26  ilesos                  455060 non-null  int64
 27  feridos_leves           455060 non-null  int64
 28  feridos_graves          455060 non-null  int64
 29  mortos                  455060 non-null  int64
 30  latitude                455060 non-null  float64
 31  longitude               455060 non-null  float64
 32  regional                455037 non-null  object
 33  delegacia               454892 non-null  object
 34  uop                     454524 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(9), object(21)
memory usage: 125.0+ MB

None

                 id         pesid                   data_inversa             br             km    id_veiculo  ano_fabricacao_veiculo          idade         ilesos  feridos_leves  feridos_graves         mortos       latitude      longitude
count  455060.00000  4.550600e+05                         455060  455060.000000  455060.000000  4.550600e+05           455060.000000  455060.000000  455060.000000  455060.000000   455060.000000  455060.000000  455060.000000  455060.000000
mean   670834.11838  1.369358e+06  2025-03-04 05:03:41.161165056     211.183125     268.202186  1.160016e+06             1834.960025      33.417624       0.392267       0.327104        0.102802       0.031031     -18.648385     -46.631066
min    571772.00000  0.000000e+00            2024-01-01 00:00:00       0.000000       0.000000  0.000000e+00                0.000000       0.000000       0.000000       0.000000        0.000000       0.000000     -33.689326     -72.835751
25%    619713.00000  1.354106e+06            2024-08-04 00:00:00     101.000000      81.000000  1.101625e+06             2007.000000      21.000000       0.000000       0.000000        0.000000       0.000000     -24.982890     -50.576593
50%    665497.00000  1.479008e+06            2025-03-03 00:00:00     163.000000     203.000000  1.191750e+06             2013.000000      34.000000       0.000000       0.000000        0.000000       0.000000     -20.225260     -47.481389
75%    723575.00000  1.604566e+06            2025-10-05 00:00:00     324.000000     421.000000  1.286620e+06             2020.000000      47.000000       1.000000       1.000000        0.000000       0.000000     -12.540656     -42.466417
max    772176.00000  1.737879e+06            2026-04-30 00:00:00     495.000000    1470.000000  1.383658e+06             2026.000000    2025.000000       1.000000       1.000000        1.000000       1.000000       4.461419     -32.406822
std     58377.94562  4.431653e+05                            NaN     127.920838     231.231042  2.360007e+05              573.047374      41.071743       0.488256       0.469156        0.303700       0.173402       7.679181       6.246490

id                            0
pesid                         0
data_inversa                  0
dia_semana                    0
horario                       0
uf                            0
br                            0
km                            0
municipio                     0
causa_acidente                0
tipo_acidente                 0
classificacao_acidente       15
fase_dia                      0
sentido_via                   0
condicao_metereologica        0
tipo_pista                    0
tracado_via                   0
uso_solo                      0
id_veiculo                    0
tipo_veiculo              14840
marca                         0
ano_fabricacao_veiculo        0
tipo_envolvido            39942
estado_fisico             39942
idade                         0
sexo                      39942
ilesos                        0
feridos_leves                 0
feridos_graves                0
mortos                        0
latitude                      0
longitude                     0
regional                     23
delegacia                   168
uop                         536
dtype: int64

## Transformando a coluna ano veículo
Olhando para as informações do discribe() é possível observar que o valor mínimo é 0, ou seja veiculos sem a informação de ano, no lugar de 0 deveria existir null para não influenciar calculos de métricas posteriormente e saber da ausência de informação

In [35]:
dataset.loc[dataset["ano_fabricacao_veiculo"] == 0, "ano_fabricacao_veiculo"] = pd.NA

## Avaliando booleanos de condição física das pessoas envolvidas
Existem 4 colunas booleanas que representam a condição física da pessoa envolvida, entretanto essa mesma informação está na coluna `estado_fisico` de forma textual

In [36]:
pd.crosstab( # para verificar se realmente as informaçõs de uma coluna estão em outra
    dataset["estado_fisico"],
    [
        dataset["ilesos"],
        dataset["feridos_leves"],
        dataset["feridos_graves"],
        dataset["mortos"]
    ]
)

dataset = dataset.drop(columns=[
    "ilesos",
    "feridos_leves",
    "feridos_graves",
    "mortos"
])

## Avaliando os valores da coluna idade

Nessa coluna tem dois problemas principais:
- Quando não existe informação de qual a idade ela é preenchida como -1, é melhor fica como NULL pois deixar esse campo com -1 pode atrapalhar o calculo de métricas posteriormente como saber qual a média de idade das pessoas que sofrem acidentes
- Existem idades que são impossíveis como por exemplo maiores que 200 anos, avaliando os dados notem que existem amostras com 127 anos depois com 225 anos, apesar de idades superiores a 110 anos já serem extremamente improváveis e a pessoa mais velha registrada ter 122 anos vou considerar o limite como 127
- um ponto que provavelmente deve ser um erro, mas não tem como saber de forma 100% correta são as pessoas com 0 anos, isso poderia indicar pessoas com menos de 1 ano de idade, entretando como esse valor detem mais de 78.000 amostras enquanto a quantidade e pessoas maiores que 0 e menor ou igual a 25 anos é de aproximadamente 73.000 leva a indicar que provavelmente esses dados foram preenchidos de forma errada

In [37]:
# analisando os valores distintos dessa coluna para saber quando existem prováveis outliers
# display(dataset["idade"].value_counts().sort_index())

# analisando a quantidade de pessoas com idade igual a 0 e comparando com outro grupo
idade_0_a_25 = dataset.loc[(dataset["idade"] <= 25) & (dataset["idade"] > 0), "idade" ].count()
idade_0 = dataset.loc[dataset["idade"] == 0, "idade"].count()
print(f"Quantidade de pessoas com 0 (zero) anos de idade: {idade_0}")
print(f"Quantidade de pessoas com idades entre 1-25 anos: {idade_0_a_25}")
# apesar de ser inprovável que a quantidade de vítimas recem nascidas seja superior as de idade entre 1-25 anos não é possível dizer que isso é um erro de forma categorica

# substituindo os valores -1 por NULL
dataset.loc[dataset["idade"] == -1, "idade"] = pd.NA

# substituindo idade impossíveis
dataset.loc[dataset["idade"] > 127, "idade"] = pd.NA

Quantidade de pessoas com 0 (zero) anos de idade: 78970
Quantidade de pessoas com idades entre 1-25 anos: 73925

## Tratando a coluna classificacao_acidente
Existem alguns valores nulos nessa coluna que possivelmente podem ser passados para um tipo dentro das categorias já existentes

In [38]:
# De acordo com o dicionário de dados existe a classificação "Ignorado" para essa coluna, vamos passar os valores NULL para essa classe
dataset["classificacao_acidente"] = dataset["classificacao_acidente"].fillna("Ignorado")

## Analisando a coluna `tracado_via`

Essa coluna pode conter múltiplos valores em uma mesma célula, separados por `;`.
Como o esquema final deve seguir o modelo estrela, não foi criada uma tabela auxiliar para armazenar os valores distintos nem uma tabela de associação entre esses valores e a tabela fato.

Por esse motivo, optou-se por criar novas colunas booleanas, cada uma representando um dos valores atômicos presentes em `tracado_via`. Cada coluna indica a presença (`1`) ou ausência (`0`) do respectivo valor.

Exemplo:

**Antes**

| tracado_via |
|-------------|
| Aclive;Curva |

**Depois**

| Aclive | Curva |
|---------|--------|
| 1 | 1 |

In [39]:
# criando uma matriz com as colunas booleanas baseadas na coluna "tracado_via"
colunas_booleanas = dataset["tracado_via"].str.get_dummies(sep=";")

# conferindo quais são os valores únicos atómicos da coluna "tracado_via" para garantir que foram geradas todas as colunas booleanas esperadas
valores_unicos = (
    dataset["tracado_via"]
    .dropna()
    .str.split(";")
    .explode()
    .unique()
)
display(valores_unicos)
display(colunas_booleanas.head())

# adicionando as novas colunas no dataset
dataset = pd.concat(
    [dataset, colunas_booleanas],
    axis=1 # para concatenar com horizontalmente e não verticalmente
)

# removendo a coluna "tracado_via" tendo em vista que já existem colunas que armaneam a informação proviniente dela
dataset.drop(columns=["tracado_via"], inplace=True)

array(['Reta', 'Curva', 'Declive', 'Aclive', 'Retorno Regulamentado',
       'Ponte', 'Viaduto', 'Interseção de Vias', 'Rotatória', 'Em Obras',
       'Desvio Temporário', 'Túnel'], dtype=object)

   Aclive  Curva  Declive  Desvio Temporário  Em Obras  Interseção de Vias  Ponte  Reta  Retorno Regulamentado  Rotatória  Túnel  Viaduto
0       0      0        0                  0         0                   0      0     1                      0          0      0        0
1       0      0        0                  0         0                   0      0     1                      0          0      0        0
2       0      1        0                  0         0                   0      0     0                      0          0      0        0
3       0      0        1                  0         0                   0      0     1                      0          0      0        0
4       0      0        0                  0         0                   0      0     1                      0          0      0        0

## Tratando os valores nulos das colunas: tipo_envolvido, stado_fisico e sexo
Como cada uma dessas colunas contem a mesma quantidade de valores nulos pode ser que sejam exatamente a mesma linha que não contem multiplas informações, uma pessoa que não contem nenhuma dessas informações pode ser caracterizada como não identificada para facilitar o entendimento das informações

In [40]:
# verificando se realmente é a mesma linha com multiplas linhas colunas vazia
filtro = (
    dataset["estado_fisico"].isna() &
    dataset["tipo_envolvido"].isna() &
    dataset["sexo"].isna()
)
print(f"quantidade de linhas que não tem informação nas colunas em questão: {filtro.sum()}")

# agora que foi mostrado que são a mesma linha vou avaliar qual a idade descrita, levando em consideração que essa é a ultima informação que sobre referente a pessoa envolvida
print(f"desas linhas quais as idades das pessoas em questão: {dataset.loc[filtro, "idade"].unique()}")

# avaliando quantos pesid distintos existem para essa pessoa
print(f"quantidade de pesid existentes para cada uma dessas linhas: {dataset.loc[filtro, "pesid"].nunique()}")

# avaliando quantos id_veiculo distintos existem para essa pessoa
print(f"quantidade de id_veiculo existentes para cada uma dessas linhas: {dataset.loc[filtro, "id_veiculo"].nunique()}")

# avaliando o tipo do veiculo envolvido pera essas pessoas
print(f"quantidade de veiculos sem tipo definido para essas pessoas: {dataset.loc[filtro, "tipo_veiculo"].isna().sum()}")

# aparentemente quando uma pessoa não é identificada ela é colocada como um ID específico e com os valores nulos nessas respectivas colunas e idade igual a 0 (zero)
# criando uma coluna nova que vai dizer se a pessoa em questão foi ou não identificada para facilitar o entendimento dos dados
dataset["identificada"] = 1
dataset.loc[filtro, "identificada"] = 0

quantidade de linhas que não tem informação nas colunas em questão: 39942
desas linhas quais as idades das pessoas em questão: [0.]
quantidade de pesid existentes para cada uma dessas linhas: 1
quantidade de id_veiculo existentes para cada uma dessas linhas: 39942
quantidade de veiculos sem tipo definido para essas pessoas: 0

In [41]:
# printando algumas informações pertinentes que ajudam a avaliar quais transformações são necessárias
display(dataset.shape)
display(dataset.head())
display(dataset.info())
display(dataset.describe())
display(dataset.isnull().sum())

(455060, 43)

         id    pesid data_inversa     dia_semana   horario  uf   br     km           municipio                                            causa_acidente                   tipo_acidente classificacao_acidente     fase_dia  sentido_via condicao_metereologica tipo_pista uso_solo  id_veiculo     tipo_veiculo                   marca  ano_fabricacao_veiculo tipo_envolvido  estado_fisico  idade       sexo   latitude  longitude regional delegacia             uop  Aclive  Curva  Declive  Desvio Temporário  Em Obras  Interseção de Vias  Ponte  Reta  Retorno Regulamentado  Rotatória  Túnel  Viaduto  identificada
0  571789.0  1269011   2024-01-01  segunda-feira  03:56:00  ES  101   38.0  CONCEICAO DA BARRA                                    Ultrapassagem Indevida  Colisão lateral sentido oposto               Ignorado  Plena Noite    Crescente              Céu Claro    Simples      Não     1018240  Caminhão-trator     M.BENZ/AXOR 2544 LS                  2014.0       Condutor          Ileso   46.0  Masculino -18.482610 -39.923790  SPRF-ES  DEL04-ES  UOP02-DEL04-ES       0      0        0                  0         0                   0      0     1                      0          0      0        0             1
1  571804.0  1269118   2024-01-01  segunda-feira  04:50:00  PI  343  185.0            PIRIPIRI                               Manobra de mudança de faixa                 Colisão frontal     Com Vítimas Fatais    Amanhecer  Decrescente              Céu Claro    Simples      Sim     1018325         Caminhão       M.BENZ/ATEGO 2426                  2019.0       Condutor          Ileso   24.0  Masculino  -4.296033 -41.767327  SPRF-PI  DEL02-PI  UOP01-DEL02-PI       0      0        0                  0         0                   0      0     1                      0          0      0        0             1
2  571806.0  1269735   2024-01-01  segunda-feira  04:30:00  BA  116  578.0             BREJOES                          Ingestão de álcool pelo condutor                 Colisão frontal     Com Vítimas Fatais  Plena Noite  Decrescente              Céu Claro    Simples      Não     1018705  Caminhão-trator        SCANIA/R450 A6X2                  2021.0       Condutor          Ileso   45.0  Masculino -13.071583 -39.961111  SPRF-BA  DEL03-BA  UOP02-DEL03-BA       0      1        0                  0         0                   0      0     0                      0          0      0        0             1
3  571818.0  1269075   2024-01-01  segunda-feira  06:30:00  SE  101   18.0    MALHADA DOS BOIS                  Reação tardia ou ineficiente do condutor       Saída de leito carroçável    Com Vítimas Feridas    Amanhecer    Crescente              Céu Claro      Dupla      Não     1018287  Caminhão-trator  IVECO/STRALIS 800S48TZ                  2022.0       Condutor  Lesões Graves   33.0  Masculino -10.356019 -36.905522  SPRF-SE  DEL02-SE  UOP02-DEL02-SE       0      0        1                  0         0                   0      0     1                      0          0      0        0             1
4  571838.0  1269159   2024-01-01  segunda-feira  05:00:00  MT  364  240.0        RONDONOPOLIS  Condutor deixou de manter distância do veículo da frente                Colisão traseira            Sem Vítimas    Pleno dia    Crescente              Céu Claro      Dupla      Não     1018348         Caminhão       SCANIA/P 310 B8X2                  2013.0       Condutor          Ileso   57.0  Masculino -16.179141 -54.789053  SPRF-MT  DEL02-MT  UOP01-DEL02-MT       0      0        0                  0         0                   0      0     1                      0          0      0        0             1

<class 'pandas.core.frame.DataFrame'>
Index: 455060 entries, 0 to 64124
Data columns (total 43 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      455060 non-null  float64
 1   pesid                   455060 non-null  int64
 2   data_inversa            455060 non-null  datetime64[ns]
 3   dia_semana              455060 non-null  object
 4   horario                 455060 non-null  object
 5   uf                      455060 non-null  object
 6   br                      455060 non-null  int64
 7   km                      455060 non-null  float64
 8   municipio               455060 non-null  object
 9   causa_acidente          455060 non-null  object
 10  tipo_acidente           455060 non-null  object
 11  classificacao_acidente  455060 non-null  object
 12  fase_dia                455060 non-null  object
 13  sentido_via             455060 non-null  object
 14  condicao_metereologica  455060 non-null  object
 15  tipo_pista              455060 non-null  object
 16  uso_solo                455060 non-null  object
 17  id_veiculo              455060 non-null  int64
 18  tipo_veiculo            440220 non-null  object
 19  marca                   455060 non-null  object
 20  ano_fabricacao_veiculo  414630 non-null  float64
 21  tipo_envolvido          415118 non-null  object
 22  estado_fisico           415118 non-null  object
 23  idade                   454742 non-null  float64
 24  sexo                    415118 non-null  object
 25  latitude                455060 non-null  float64
 26  longitude               455060 non-null  float64
 27  regional                455037 non-null  object
 28  delegacia               454892 non-null  object
 29  uop                     454524 non-null  object
 30  Aclive                  455060 non-null  int64
 31  Curva                   455060 non-null  int64
 32  Declive                 455060 non-null  int64
 33  Desvio Temporário       455060 non-null  int64
 34  Em Obras                455060 non-null  int64
 35  Interseção de Vias      455060 non-null  int64
 36  Ponte                   455060 non-null  int64
 37  Reta                    455060 non-null  int64
 38  Retorno Regulamentado   455060 non-null  int64
 39  Rotatória               455060 non-null  int64
 40  Túnel                   455060 non-null  int64
 41  Viaduto                 455060 non-null  int64
 42  identificada            455060 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(16), object(20)
memory usage: 152.8+ MB

None

                 id         pesid                   data_inversa             br             km    id_veiculo  ano_fabricacao_veiculo          idade       latitude      longitude         Aclive          Curva        Declive  Desvio Temporário       Em Obras  Interseção de Vias          Ponte           Reta  Retorno Regulamentado      Rotatória          Túnel        Viaduto   identificada
count  455060.00000  4.550600e+05                         455060  455060.000000  455060.000000  4.550600e+05           414630.000000  454742.000000  455060.000000  455060.000000  455060.000000  455060.000000  455060.000000      455060.000000  455060.000000       455060.000000  455060.000000  455060.000000          455060.000000  455060.000000  455060.000000  455060.000000  455060.000000
mean   670834.11838  1.369358e+06  2025-03-04 05:03:41.161165056     211.183125     268.202186  1.160016e+06             2013.884449      32.557024     -18.648385     -46.631066       0.092183       0.180352       0.118754           0.004470       0.024381            0.073408       0.012194       0.733341               0.026408       0.024896       0.000527       0.015481       0.912227
min    571772.00000  0.000000e+00            2024-01-01 00:00:00       0.000000       0.000000  0.000000e+00             1900.000000       0.000000     -33.689326     -72.835751       0.000000       0.000000       0.000000           0.000000       0.000000            0.000000       0.000000       0.000000               0.000000       0.000000       0.000000       0.000000       0.000000
25%    619713.00000  1.354106e+06            2024-08-04 00:00:00     101.000000      81.000000  1.101625e+06             2009.000000      21.000000     -24.982890     -50.576593       0.000000       0.000000       0.000000           0.000000       0.000000            0.000000       0.000000       0.000000               0.000000       0.000000       0.000000       0.000000       1.000000
50%    665497.00000  1.479008e+06            2025-03-03 00:00:00     163.000000     203.000000  1.191750e+06             2014.000000      34.000000     -20.225260     -47.481389       0.000000       0.000000       0.000000           0.000000       0.000000            0.000000       0.000000       1.000000               0.000000       0.000000       0.000000       0.000000       1.000000
75%    723575.00000  1.604566e+06            2025-10-05 00:00:00     324.000000     421.000000  1.286620e+06             2021.000000      47.000000     -12.540656     -42.466417       0.000000       0.000000       0.000000           0.000000       0.000000            0.000000       0.000000       1.000000               0.000000       0.000000       0.000000       0.000000       1.000000
max    772176.00000  1.737879e+06            2026-04-30 00:00:00     495.000000    1470.000000  1.383658e+06             2026.000000     127.000000       4.461419     -32.406822       1.000000       1.000000       1.000000           1.000000       1.000000            1.000000       1.000000       1.000000               1.000000       1.000000       1.000000       1.000000       1.000000
std     58377.94562  4.431653e+05                            NaN     127.920838     231.231042  2.360007e+05                8.341989      20.563964       7.679181       6.246490       0.289285       0.384481       0.323499           0.066707       0.154230            0.260805       0.109751       0.442213               0.160344       0.155807       0.022959       0.123458       0.282965

id                            0
pesid                         0
data_inversa                  0
dia_semana                    0
horario                       0
uf                            0
br                            0
km                            0
municipio                     0
causa_acidente                0
tipo_acidente                 0
classificacao_acidente        0
fase_dia                      0
sentido_via                   0
condicao_metereologica        0
tipo_pista                    0
uso_solo                      0
id_veiculo                    0
tipo_veiculo              14840
marca                         0
ano_fabricacao_veiculo    40430
tipo_envolvido            39942
estado_fisico             39942
idade                       318
sexo                      39942
latitude                      0
longitude                     0
regional                     23
delegacia                   168
uop                         536
Aclive                        0
Curva                         0
Declive                       0
Desvio Temporário             0
Em Obras                      0
Interseção de Vias            0
Ponte                         0
Reta                          0
Retorno Regulamentado         0
Rotatória                     0
Túnel                         0
Viaduto                       0
identificada                  0
dtype: int64